### ISSUE TITLE
Update emulsify-gulp dependencies to remove warnings on install

### ISSUE THREAD

**Issue by ebremner17** [fourkitchens/emulsify-gulp#111]
When installing pattern-lab and using emulsify-gulp v4.0.0, there are some warnings about deprecated modules.
![screen shot 2019-02-28 at 8 14 52 am](https://user-images.githubusercontent.com/14892867/53569650-a5f1c680-3b32-11e9-847e-610a81dcd818.png)

Can we please get those updated/fixed?

**Comment by dasginganinja** [comment]
+1

**Comment by amyh** [comment]
+1

**Comment by amyh** [comment]
When I run `npm start` in my custom theme's directory, I get this error:
```
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/web/themes/custom/my_theme/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/web/themes/custom/my_theme/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/web/themes/custom/my_theme/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! emulsify@1.0.0 start: `gulp compile && gulp theme`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the emulsify@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
I'm working inside Lando, if that is significant.

**Comment by evanmwillhite** [comment]
This may be related to certain Node versions with our Gulp version (3). I ran a fresh install locally on master and ran into issues with Node 12 and 11 but not 10 if that helps.

PRs are always welcome, but all our current development efforts at Four Kitchens are going into the new Emulsify Design System that we hope to release in the next two months. This will use Storybook instead of Pattern Lab and include a new Styleguide tool using Gatsby. Also, the build system (what currently uses Gulp) is entirely replaced with Webpack. The upgrade process for older Emulsify instances will be straightforward, and we will document it upon release. Thanks!

**Comment by amyh** [comment]
Thanks! I rolled node back to 10.17, and that got rid of the problem.
