### ISSUE TITLE
Can't have multiple serving instances

### ISSUE THREAD

**Issue by EvanLovely** [fourkitchens/emulsify-gulp#32]
I often clone the same repo twice so I have a Pattern Lab running that shows `develop` and another on my feature branch so I can make sure I don't break stuff. However, this setup doesn't let multiple instances be ran. Perhaps something as simple as exposing the option to configure the port Browser Sync uses?

<details>

<summary>Error message surrounding `Error: listen EADDRINUSE :::3000`</summary>

```bash
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)
    at Server.listen (net.js:1390:5)
    at module.exports.plugin (/Users/Evan/dev/clients/thenextsystem2/web/themes/custom/emulsify/node_modules/browser-sync/lib/server/index.js:36:25)
    at Object.startServer [as fn] (/Users/Evan/dev/clients/thenextsystem2/web/themes/custom/emulsify/node_modules/browser-sync/lib/async.js:195:52)
    at /Users/Evan/dev/clients/thenextsystem2/web/themes/custom/emulsify/node_modules/browser-sync/lib/browser-sync.js:149:14
    at iterate (/Users/Evan/dev/clients/thenextsystem2/web/themes/custom/emulsify/node_modules/browser-sync/lib/utils.js:276:13)
    at /Users/Evan/dev/clients/thenextsystem2/web/themes/custom/emulsify/node_modules/browser-sync/lib/utils.js:285:25
error Command failed with exit code 1.
```

</details>

**Comment by evanmwillhite** [comment]
Yea, this is something I've been meaning to work on. Issue https://github.com/fourkitchens/emulsify-gulp/issues/15 already exists for it, so I'll close this one, but thanks for the reminder.
